### ISSUE TITLE
ValueError: Could not find associated confound file. The functional derivatives should exist under the same parent directory.

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/giga_connectome#26]
Entity `acq` cannot be recongnised correctly

This is an upstream issue. Will be fix by the next release of nilearn

Open issue for book keeping.

Dataset: abide2 ONRC_2

https://github.com/nilearn/nilearn/pull/3794

**Comment by Remi-Gau** [comment]
Fixing required bumping nilearn version
