### ISSUE TITLE
Flowchart to explain the process

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/giga_connectome#3]
This will provide a common ground for discussion

**Comment by Remi-Gau** [comment]
Would this be figure to illustrate thie: https://giga-connectome.readthedocs.io/en/stable/workflow.html

**Comment by htwangtw** [comment]
![giga_connectome](https://github.com/SIMEXP/giga_connectome/assets/13743617/5c728c1f-d10e-4a0c-b8ee-1065b2bf2a13)
Something like this - need to update

**Comment by Remi-Gau** [comment]
you got an svg of this?

**Comment by htwangtw** [comment]
I used draw.io to make this - it's an xml I believe
