### ISSUE TITLE
How to handle multiple tasks when generating group connetomes

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/giga_connectome#33]
The current behaviour is one atlas parcellation scheme, one group atlas.
Hence for case like ds000017, it disregard task and session. 

Other potential options:
1. don't provide group average at all.
2. per session, per task
3. per task.

**Comment by Remi-Gau** [comment]
At first approach, we can say it is the responsibility of the user to pass the correct bids filter.
If we see that several tasks are being averaged we could at least throw a warning.

**Comment by htwangtw** [comment]
Let's go with throw a warning for now

**Comment by htwangtw** [comment]
This is no longer relevant as group will not be an available option see #112
