### ISSUE TITLE
Missing confounds file, unable to complete

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/giga_connectome#54]
For OASIS, I am now getting the following error:

`ValueError: Could not find associated confound file. The functional derivatives should exist under the same parent directory.
`

I ran a script to see which subjects were missing confound files and then excluded them from the list of participants. However, I still get the error. What's odd is that sometimes the job completes, but sometimes it fails - either way the hdf5 file never gets created so I can't check that to see which subjects are missing and might be causing the issue. 

Any ideas what else I could do @htwangtw ? Thank you!

**Comment by htwangtw** [comment]
Can you post an example file name? There's a chance that there are entities not recognised by the current lazy confound file search....

**Comment by clarkenj** [comment]
OASIS did have some weird naming, like `sub-OAS31464_ses-d0014_task-restMB4_run-1_desc-confounds_timeseries.tsv` for some subjects, would that be it?

**Comment by htwangtw** [comment]
Can you give me a few examples with their preprocessed bold image counterparts?
Alternatively you can run at participant level on a few to see which subjects failed. It's a costly way to debug but should get us a better idea

**Comment by clarkenj** [comment]
```
sub-OAS31464_ses-d0014_task-restMB4_run-1_desc-confounds_timeseries.tsv
sub-OAS31464_ses-d0014_task-restMB4_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
sub-OAS31464_ses-d0014_task-restMB4_run-1_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz

sub-OAS31464_ses-d0014_task-rest_run-2_desc-confounds_timeseries.tsv
sub-OAS31464_ses-d0014_task-rest_run-2_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
sub-OAS31464_ses-d0014_task-rest_run-2_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz

sub-OAS30385_ses-d0112_task-rest_run-1_desc-confounds_timeseries.tsv
sub-OAS30385_ses-d0112_task-rest_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
sub-OAS30385_ses-d0112_task-rest_run-1_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz
```

How's this? Let me know if you think I should just go ahead with running at the participant level

**Comment by htwangtw** [comment]
Things look really reasonable... 
I guess we have to run participant level to find out more
Thanks for investigating this!

**Comment by clarkenj** [comment]
OK I'll do that, thanks very much!

**Comment by clarkenj** [comment]
I am running into an issue, because for the other datasets I ran at the participant level I was able to build the bids database first at the group level. If I just go straight to running OASIS at the participant level without this I get the database is locked error. Maybe I am missing something about the correct way to run at the participant level? Thanks!

**Comment by htwangtw** [comment]
are you re-indexing on the same bids data set with different jobs? that's the most likely reason

**Comment by htwangtw** [comment]
Once the data base is built, you don't need to do it again. 

For now, no matter if it's participant level or group level, the database building is the same. 

So you need to:
1. Run one participant and use the reindex option
2. Run the remaining without the reindex option


I need to think about how to make this experience smoother without duplicating the database building process.

**Comment by clarkenj** [comment]
Ahh Ok, I didn't realise building it on only one participant would work. Thanks!

**Comment by htwangtw** [comment]
@clarkenj based on the meeting today, can we mark this as resolved?
