### ISSUE TITLE
use mypy to check type hints?

### ISSUE THREAD

**Issue by Remi-Gau** [SIMEXP/giga_connectome#65]
Given that there is already some type annotation this may be useful.

What do you think?

**Comment by htwangtw** [comment]
I didn't know this project! Looks nice why not. The project description on pypi has a different flavour comparing to the docs
![image](https://github.com/SIMEXP/giga_connectome/assets/13743617/22629b1f-b744-4165-a002-e7fde8c192ad)

**Comment by Remi-Gau** [comment]
OK I can try to set it up
