### ISSUE TITLE
add nilearn reports in the output

### ISSUE THREAD

**Issue by Remi-Gau** [SIMEXP/giga_connectome#66]
Given that nilearn can generate several reports, it may be worth some to the output for visualization / QC.

This may also highlight what type of reports would be useful and that nilearn cannot yet generate.

**Comment by htwangtw** [comment]
I didn't look into the report since the original aim was to deploy these on HPC on 40k subjects easily, but it won't harm having the reports. Also just good to know what helps nilearn!
