### ISSUE TITLE
build the doc on PR

### ISSUE THREAD

**Issue by Remi-Gau** [SIMEXP/giga_connectome#68]
Should help catch issues early

Should be toggled here: https://readthedocs.org/dashboard/giga_connectome/advanced/

![image](https://github.com/SIMEXP/giga_connectome/assets/6961185/d98a4b4a-b10e-4d20-bd3b-012dbff6244b)

See the doc: https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by htwangtw** [comment]
The option has been toggled. Shall we close this one?

**Comment by Remi-Gau** [comment]
It works


![image](https://github.com/SIMEXP/giga_connectome/assets/6961185/8461f1c1-5408-4c04-b891-83f72d6ebd6c)


https://readthedocs.org/projects/giga-connectome/builds/22857983/
