### ISSUE TITLE
a rerun of the app should overwrite previous results

### ISSUE THREAD

**Issue by Remi-Gau** [SIMEXP/giga_connectome#76]
Playing around with the app and the test data I am getting files with an extra suffix.

Probably better to overwrite previous results, no?

```
tree giga_connectome/data/test_data/output 

giga_connectome/data/test_data/output
├── sub-1_atlas-Schaefer20187Networks_desc-simple_1.h5
├── sub-1_atlas-Schaefer20187Networks_desc-simple_2.h5
├── sub-1_atlas-Schaefer20187Networks_desc-simple_3.h5
├── sub-1_atlas-Schaefer20187Networks_desc-simple_4.h5
├── sub-1_atlas-Schaefer20187Networks_desc-simple_5.h5
├── sub-1_atlas-Schaefer20187Networks_desc-simple_6.h5
└── sub-1_atlas-Schaefer20187Networks_desc-simple.h5
```

**Comment by htwangtw** [comment]
Yep that's old relic... I am thinking should we throw error if user intends to overwrite? What do other bids apps do?

**Comment by Remi-Gau** [comment]
they usually overwrite

we could:
- overwrite silently
- overwrite with warning
- not overwrite and throw error
- overwrite only if a --force argument is passed

For now I would overwrite with warning and see if users complain.

**Comment by htwangtw** [comment]
okay let's do overwrite with warning
