### ISSUE TITLE
Remove group level analysis option to simplify the function

### ISSUE THREAD

**Issue by Remi-Gau** [SIMEXP/giga_connectome#79]
Usually BIDS app do not rerun participant level things when a group level is requested.

- participant level -> process each participant requested
- group level -> combine data from participants that are already processed

Unless I am mistaken currently the app always runs participant level first even if group is requested.

**Comment by htwangtw** [comment]
I took some liberty in the definition of participant vs group 
We can certainly discuss what's the better way to move forward.

The current behaviour:
- participant level: generate *subject* specific grey matter and atlas, generate time series and connectome per subject.
- group level: generate *dataset* specific grey matter and atlas (applied across subjects in the same dataset), generate time series and connectome per subject, *generate group average connectome*

The reason of generating *dataset* specific grey matter and atlas is for reducing run time for small to medium sized dataset, and to make sure all the subjects will have the same parcels per atlas.
For really large ones like UKBB we have no choice but do everything at participant level. 

If we correct this to fit BIDS App requirement, obviously we will drop the dataset specific grey matter and atlas. If the group level command can aggregate all singular h5 files per subject into a collective one that would be nice too... 

I have considered dropping the averaged group connectome as I found them not practical in analysis - we might drop some subjects during the analysis stage, and it's really quick to recalculate this. @clarkenj what's your experience with the connectome generated? Are they useful at all?

**Comment by clarkenj** [comment]
The averaged group connectome? I haven't used them yet but for my use case I don't think I will!

**Comment by htwangtw** [comment]
Let's remove the group option all together. 
This is not very useful, it's not very scalable, and the improvement is marginal.

**Comment by arovai** [comment]
Hello!
I was personally quite interested in having such group analysis tools... for instance, if I have two populations (or two sessions) and wish to compare their connectomes, it seems necessary to do some sort of group-level analysis to spot statistically significant differences, no?
Such tools exists by other software like CONN, by the way (but I'd rather use nilearn).
The way I see it is for instance to have the group-level model defined in a json file and have giga_connectome (...) (...) group --config /path/to/config do the job.
